import type { Metadata } from "next";
import { Aleo } from "next/font/google";

import Nav from "./components/Nav/Nav";
import SectionContainer from "./components/Layout/SectionContainer";
import Footer from "./components/Footer/Footer";

import "./globals.css";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aleo.className} flex flex-col min-h-screen bg-grey-500 text-textColor`}
      >
        <Nav />
        <SectionContainer customClasses="my-[60px] flex-1">
          {children}
        </SectionContainer>
        <Footer />
      </body>
    </html>
  );
}
