import type { Metadata } from "next";
import { Aleo } from "next/font/google";

import Nav from "./_components/Nav/Nav";
import Footer from "./_components/Footer/Footer";
import { CategoriesNav } from "./_components/CategoriesNav/CategoriesNav";
import { isMobileDeviceSSR } from "./_utils/serverResponsive";

import { MOCK_CATEGORIES } from "./_mock/mock";

import "./globals.css";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = isMobileDeviceSSR();
  return (
    <html lang="en">
      <body
        className={`${aleo.className} flex flex-col min-h-screen bg-grey-500 text-textColor`}
      >
        <Nav />
        {!isMobile && <CategoriesNav links={MOCK_CATEGORIES} />}
        {children}
        <Footer />
      </body>
    </html>
  );
}
